### ISSUE TITLE
1.1.2 Pypi version differs from the repository

### ISSUE THREAD

**Issue by aleray** [MinchinWeb/minchin.pelican.plugins.image_process#2]
Hi,

for some reasons the version hosted on Pypi slightly differs from the one on the repository. It tries to support animated GIFs but results in broken PNG support (at least).

Line 536/537 of `image_process.py` differ. Pypi version uses `i.save(image[1], save_all=True)` whereas git version uses `i.save(image[1])`.

Could you have a look?

thanks

**Comment by minchinweb** [comment]
Good catch. Yes, somehow, the code on PyPI and here diverged. Version 1.1.3 has been released to fix the issue.

I would love to get animated GIF resizing working, but it's proving surprisingly involved...

**Comment by aleray** [comment]
Thanks!
